import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ar' | 'en';

export interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
  t: (key: string) => string;
  isRTL: boolean;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Common & Navbar
    appName: 'إصلاح',
    back: 'رجوع',
    adminDashboard: 'لوحة تحكم الأدمن',
    serviceHistory: 'سجل الخدمات',
    myProfile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    loading: 'جاري التحميل...',
    cancel: 'إلغاء',
    save: 'حفظ',
    saveChanges: 'حفظ التغييرات',
    saving: 'جاري الحفظ...',
    refresh: 'تحديث',
    refreshFeeds: 'تحديث القائمة',
    accountBanned: 'الحساب محظور',
    accountBannedMsg: 'تم حظر هذا الحساب من قِبل إدارة التطبيق.',
    notRatedYet: 'لم يتم التقييم بعد',
    switchLangText: 'English',
    liveChat: '🔴 المحادثة الفورية',
    sendMyLocation: '📍 إرسال موقعي الحالي',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    noMessages: 'لا توجد رسائل بعد',
    locationSent: 'تم إرسال الموقع 📍:',
    openInGoogleMaps: 'فتح في خرائط جوجل',
    yes: 'نعم',
    no: 'لا',

    // AuthPage
    welcomeBack: 'مرحباً بك مجدداً في إصلاح',
    createAccount: 'إنشاء حساب جديد',
    signIn: 'تسجيل الدخول',
    register: 'تسجيل حساب',
    fullName: 'الاسم بالكامل',
    fullNamePlaceholder: 'أدخل اسمك بالكامل',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    role: 'نوع الحساب',
    customerRole: 'عميل',
    technicianRole: 'فني صيانة',
    phoneNumber: 'رقم الهاتف',
    phoneNumberPlaceholder: 'أدخل رقم الهاتف',
    password: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    authFailed: 'فشل التحقق من الحساب. يرجى التأكد من صحة البيانات.',

    // Vehicles
    SEDAN: 'سيدان',
    SUV: 'سيارة عائلية (SUV)',
    MOTORCYCLE: 'موتوسيكل',
    HEAVY_TRUCK: 'شاحنة / نقل ثقيل',
    BUS: 'حافلة / أوتوبيس',

    // Malfunctions
    ELECTRICAL: 'كهرباء سيارات',
    MECHANICAL: 'ميكانيكا',
    TIRE_AND_WHEEL: 'إطارات وعجلات',
    BODY_AND_CHASSIS: 'سمكرة وشاسيه',
    BATTERY_JUMP: 'شحن البطارية',
    TOWING: 'ونش إنقاذ وسحب',

    // CustomerDashboard
    selectVehicle: '1. اختر نوع المركبة',
    selectIssue: '2. اختر نوع العطل',
    gpsLocationTitle: '3. تحديد الموقع الجغرافي عبر GPS (خرائط جوجل)',
    gpsAutoDesc: 'يتم جلب الرابط تلقائياً لضمان دقة خرائط جوجل دون تعديل يدوي',
    gpsNotCaptured: 'اضغط على زر (تحديد موقعي الحالي) لجلب إحداثيات GPS تلقائياً...',
    gpsCapturedSuccess: 'تم التقاط إحداثيات الموقع بدقة بنجاح ✓',
    manualAddressTitle: '4. وصف الموقع والعنوان يدوياً',
    manualAddressPlaceholder: 'اكتب وصفاً إضافياً للمكان (مثال: بجوار كوبري كذا، أمام محطة وقود، في اتجاه كذا...)',
    currentLocationTitle: '3. الموقع الحالي أو رابط الخرائط',
    useCurrentLocation: 'تحديد موقعي الحالي (GPS)',
    locating: 'جاري التحديد...',
    locationPlaceholder: 'مثال: الصق رابط خرائط جوجل... أو اكتب عنوان موقعك الحالي...',
    locationRequiredAlert: 'يرجى تحديد موقعك عبر GPS أو كتابة العنوان يدوياً لإتمام الطلب.',
    customerCancelledToast: 'قام العميل بإلغاء طلب الصيانة.',
    issueDetailsTitle: '5. تفاصيل العطل أو المشكلة',
    issuePlaceholder: 'مثال: سخونة شديدة في الموتور، عطل مفاجئ في الإطار، البطارية لا تعمل...',
    requestHelpBtn: 'طلب مساعدة طوارئ على الطريق',
    dispatching: 'جاري الإرسال...',
    requestCreatedSuccess: 'تم إنشاء طلب المساعدة بنجاح!',
    geoNotSupported: 'خاصية تحديد الموقع غير مدعومة في متصفحك.',
    geoError: 'تعذر جلب موقعك، يرجى تفعيل إذن الوصول للموقع (GPS).',
    activeRequestTitle: 'طلب المساعدة النشط',
    statusQueued: 'قيد البحث عن فنيين',
    statusPending: 'قيد الانتظار',
    statusDispatching: 'جاري توجيه الفني',
    statusAccepted: 'تم قبول الفني (في الطريق إليك)',
    statusArrived: 'وصل الفني إلى موقعك',
    statusInProgress: 'جاري تصليح المركبة',
    statusCompleted: 'مكتمل',
    statusCancelled: 'ملغي',
    vehicleType: 'نوع المركبة',
    locationNotes: 'ملاحظات وتفاصيل الموقع',
    openGoogleMaps: '📍 فتح الموقع على خرائط جوجل',
    assignedTech: 'الفني المعتمد للطلب',
    name: 'الاسم',
    phone: 'رقم الهاتف',
    workplace: 'مكان العمل / الورشة',
    serviceStatus: 'حالة الخدمة',
    onTheWay: 'الفني في الطريق إليك',
    arrivedAtLocation: 'وصل الفني إلى موقعك',
    currentlyRepairing: 'جاري العمل وتصليح العطل الآن',
    workCompleted: 'تم الانتهاء من العمل بنجاح',
    offersReceived: 'عروض المساعدة المتاحة من الفنيين',
    waitingForOffers: 'جاري انتظار عروض الفنيين القريبين منك...',
    acceptOffer: 'قبول العرض',
    rejectOffer: 'رفض',
    viewProfile: 'عرض الملف المهني',
    offerRejected: 'تم رفض العرض',
    techAcceptedToast: 'تم قبول الفني! المساعدة في الطريق إليك.',
    cancelRequestConfirm: 'هل أنت متأكد من رغبتك في إلغاء هذا الطلب؟',
    cancelRequestBtn: 'إلغاء الطلب',
    requestCancelledSuccess: 'تم إلغاء الطلب بنجاح',
    cancelJobConfirm: 'هل أنت متأكد من رغبتك في إلغاء هذه المهمة وإعادتها لقائمة الانتظار؟',
    cancelJobBtn: 'إلغاء المهمة',
    jobCancelledSuccess: 'تم إلغاء المهمة بنجاح وإعادتها لقائمة الانتظار.',
    rateServiceTitle: 'تقييم الخدمة (إجباري)',
    rateServiceDesc: 'يرجى تقييم الفني لإتمام الخدمة والتمكن من طلب مساعدة جديدة.',
    workQualityRating: 'جودة العمل والكفاءة (1-5)',
    priceFairnessRating: 'مناسبة وعدالة السعر (1-5)',
    optionalFeedback: 'ملاحظات أو تعليق اختياري...',
    submitRating: 'إرسال التقييم',
    thankYouRating: 'شكراً لتقييمك!',
    techProfileModalTitle: 'الملف المهني للفني',
    experience: 'سنوات الخبرة',
    toolsEquipment: 'امتلاك العُدة والمعدات',
    yesEquipped: 'نعم (مجهز بالكامل)',
    completedJobs: 'الطلبات المكتملة',
    overallRating: 'التقييم العام',
    qualityRating: 'تقييم الجودة',
    priceRating: 'عدالة السعر',
    vehicleSpecialties: 'تخصص المركبات',
    malfunctionSpecialties: 'تخصص الأعطال',
    allVehicles: 'جميع المركبات',
    allMalfunctions: 'جميع الأعطال',
    previousReviews: 'تقييمات وآراء العملاء السابقين',
    noReviewsYet: 'لا توجد تقييمات سابقة لهذا الفني بعد.',
    newOfferReceived: 'فني جديد أرسل لك عرض مساعدة!',
    requestStatusUpdated: 'تم تحديث حالة الطلب:',
    errorLoadingProfile: 'حدث خطأ أثناء تحميل الملف المهني',
    jobsCount: 'طلب',
    assistanceSuffix: 'صيانة ومساعدة',
    independentSpecialist: 'فني مستقل',

    // TechnicianDashboard
    techCenterTitle: 'لوحة تحكم الفني ',
    specialties: 'التخصصات',
    editSpecialties: 'تعديل التخصصات',
    activeJobTitle: 'طلب نشط تحت التنفيذ',
    customer: 'العميل',
    openCustomerMaps: 'فتح موقع العميل على خرائط جوجل (Google Maps)',
    startRoute: 'ابدأ المسار',
    issueDetails: 'تفاصيل العطل:',
    markAsArrived: 'وصلت لموقع العميل',
    startRepair: 'بدء عملية التصليح',
    completeJob: 'تم إكمال التصليح بنجاح',
    availableRequests: 'الطلبات المتاحة في منطقتك',
    noQueuedRequests: 'لا توجد طلبات معلقة حالياً تطابق تخصصك في منطقتك.',
    offersCount: 'العروض المقدمة:',
    offerSentWaiting: 'تم إرسال العرض (في انتظار اختيار العميل)',
    sendOffer: 'إرسال عرض مساعدة',
    completeActiveFirst: 'أكمل طلبك الحالي أولاً',
    sending: 'جاري الإرسال...',
    offerSentSuccess: 'تم إرسال عرض المساعدة للعميل! في انتظار موافقة العميل.',
    jobCompletedToast: 'تم إنهاء المهمة بنجاح! في انتظار تقييم العميل.',
    completeProfileTitle: 'استكمال وتعديل الملف المهني للفني',
    specifySpecialtiesDesc: 'حدد تخصصاتك وبيانات ورشتك لتتمكن من استقبال طلبات الصيانة المناسبة لك.',
    registeredPhone: 'رقم الهاتف المسجل:',
    workplacePlaceholder: 'مثال: ورشة الصفا للسيارات / فني مستقل',
    experiencePlaceholder: 'مثال: 5+ سنوات خبرة في صيانة كهرباء وميكانيكا السيارات',
    hasToolsCheckbox: 'أمتلك عُدّة ومعدات التصليح الخاصة بي',
    selectVehiclesPrompt: 'تخصص المركبات (يمكنك اختيار أكثر من نوع):',
    selectMalfunctionsPrompt: 'تخصص الأعطال (يمكنك اختيار أكثر من تخصص):',
    saveProfileBtn: 'حفظ بيانات الملف المهني',
    profileSavedSuccess: 'تم حفظ بيانات الملف المهني بنجاح!',
    custAcceptedOffer: 'العميل قبل عرضك! تم تعيين الطلب لك.',
    selectSpecialtiesAlert: 'يرجى اختيار تخصص مركبة واحد على الأقل وتخصص عطل واحد على الأقل.',
    techPhone: 'هاتف الفني:',
    workplaceOrWorkshop: 'مكان العمل / الورشة',
    careerExperience: 'سنوات الخبرة والمهنة',
    vehicleLabel: 'المركبة:',
    addressUnlisted: 'تفاصيل العنوان غير محددة',

    // AdminDashboard
    adminPanelTitle: 'لوحة تحكم إدارة النظام',
    tabDashboard: 'الإحصائيات العامة',
    tabTransactions: 'الطلبات والعمليات',
    tabCustomers: 'العملاء',
    tabTechnicians: 'الفنيون',
    totalRequests: 'إجمالي الطلبات',
    totalUsers: 'إجمالي المستخدمين',
    completedStat: 'المكتملة',
    cancelledStat: 'الملغاة',
    inProgressStat: 'قيد التنفيذ',
    dispatchedStat: 'تم التوجيه',
    queuedStat: 'قيد الانتظار',
    customersStat: 'العملاء',
    techniciansStat: 'الفنيون',
    requestsOverview: 'نظرة عامة على الطلبات',
    usersBreakdown: 'توزيع المستخدمين',
    techPresence: 'حالة اتصال الفنيين',
    onlineTechs: 'متصل الآن',
    offlineTechs: 'غير متصل',
    allStatuses: 'جميع الحالات',
    allCategories: 'جميع الفئات',
    filterAndSort: 'تصفية وترتيب:',
    allTechnicians: 'جميع الفنيين',
    topOverallRating: '⭐ الأعلى تقييماً عاماً',
    highestQuality: 'الأعلى في جودة العمل',
    bestPrice: 'الأفضل في عدالة السعر',
    notRatedYetFilter: 'لم يتم تقييمهم بعد',
    searchTechnician: 'بحث عن فني بالاسم أو الهاتف...',
    banned: 'محظور',
    active: 'نشط (متصل)',
    inactive: 'غير نشط (أوفلاين)',
    banUser: 'حظر المستخدم',
    unbanUser: 'إلغاء حظر المستخدم',
    customerReviewsTitle: 'آراء وتعليقات العملاء',
    noReviewsAdmin: 'لا توجد تقييمات أو تعليقات مسجلة لهذا الفني بعد.',
    monthlyPerformance: 'أداء الطلبات المكتملة شهرياً',
    accountStatus: 'حالة الحساب:',
    presence: 'حالة الاتصال:',
    valid: 'ساري',
    allJobsServiced: 'الطلبات المنفذة بواسطة الفني',
    customerRequestsMade: 'الطلبات المنشأة بواسطة العميل',
    tableId: 'المعرف',
    tableDate: 'التاريخ',
    tableCustomer: 'العميل',
    tableTechnician: 'الفني',
    tableStatus: 'الحالة',
    tableService: 'الخدمة',
    unassigned: 'غير محدد',
    workshopLabel: 'الورشة:',
    qualityShort: 'الجودة',
    priceShort: 'السعر',
    userDetails: 'تفاصيل',
    toolsAvailable: 'العدة متوفرة:',

    // ProfilePage
    adminSecurityGate: 'بوابة أمان الأدمن',
    adminSecurityDesc: 'يرجى إدخال كلمة المرور للوصول إلى الملف الشخصي.',
    unlockProfile: 'فتح الملف الشخصي',
    verifying: 'جاري التحقق...',
    editProfile: 'تعديل البيانات',
    techProDetails: 'بيانات وتخصصات الفني المهنية',
    profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح!',
    profileUpdateFailed: 'فشل تحديث الملف الشخصي.',
    hasToolsFull: 'أمتلك عُدة ومعدات صيانة وإصلاح متكاملة على الطريق',
    workplaceCompany: 'مكان العمل / الشركة',
    workplaceCompanyPlaceholder: 'مثال: مركز المدينة للسيارات / مستقل',
    incorrectPassword: 'كلمة المرور غير صحيحة',

    // HistoryDashboard
    pastTransactions: 'سجل العمليات السابقة',
    noPastTransactions: 'لا توجد عمليات مسجلة حتى الآن.',
    performanceChart: 'مخطط الأداء',
    requestsActivity: 'نشاط طلباتي',
    myHistoryTitle: 'سجل معاملاتي',
    last30Days: '(آخر 30 يوماً)',
  },

  en: {
    // Common & Navbar
    appName: 'Eslaah',
    back: 'Back',
    adminDashboard: 'Admin Dashboard',
    serviceHistory: 'Service History',
    myProfile: 'My Profile',
    logout: 'Logout',
    loading: 'Loading...',
    cancel: 'Cancel',
    save: 'Save',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    refresh: 'Refresh',
    refreshFeeds: 'Refresh Feeds',
    accountBanned: 'Account Banned',
    accountBannedMsg: 'This account has been banned by administrators.',
    notRatedYet: 'Not rated yet',
    switchLangText: 'عربي',
    liveChat: '🔴 Live Chat',
    sendMyLocation: '📍 Send My Location',
    typeMessage: 'Type a message...',
    send: 'Send',
    noMessages: 'No messages yet',
    locationSent: 'Location Sent 📍:',
    openInGoogleMaps: 'Open in Google Maps',
    yes: 'Yes',
    no: 'No',

    // AuthPage
    welcomeBack: 'Welcome back to Eslaah',
    createAccount: 'Create an Account',
    signIn: 'Sign In',
    register: 'Register',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email Address',
    emailPlaceholder: 'Enter your email address',
    role: 'Role',
    customerRole: 'Customer',
    technicianRole: 'Technician',
    phoneNumber: 'Phone Number',
    phoneNumberPlaceholder: 'Enter your phone number',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    authFailed: 'Authentication failed. Please check your credentials.',

    // Vehicles
    SEDAN: 'Sedan',
    SUV: 'SUV',
    MOTORCYCLE: 'Motorcycle',
    HEAVY_TRUCK: 'Truck',
    BUS: 'Bus',

    // Malfunctions
    ELECTRICAL: 'Electrical',
    MECHANICAL: 'Mechanical',
    TIRE_AND_WHEEL: 'Flat Tire',
    BODY_AND_CHASSIS: 'Body & Chassis',
    BATTERY_JUMP: 'Dead Battery',
    TOWING: 'Towing Service',

    // CustomerDashboard
    selectVehicle: '1. Select Vehicle Type',
    selectIssue: '2. Select Issue Type',
    gpsLocationTitle: '3. GPS Geographic Location (Google Maps)',
    gpsAutoDesc: 'Google Maps link is fetched automatically to prevent invalid manual edits',
    gpsNotCaptured: 'Click (Detect My Location) to capture GPS coordinates automatically...',
    gpsCapturedSuccess: 'GPS Location coordinates captured accurately ✓',
    manualAddressTitle: '4. Manual Address & Landmark Description',
    manualAddressPlaceholder: 'Write descriptive details (e.g., near bridge, opposite gas station, driving towards...)',
    currentLocationTitle: '3. Current Location or Maps Link',
    useCurrentLocation: 'Detect My Location (GPS)',
    locating: 'Locating...',
    locationPlaceholder: 'e.g. Paste Google Maps link... OR Enter your current location address...',
    locationRequiredAlert: 'Please detect your GPS location or provide a manual address to submit the request.',
    customerCancelledToast: 'Customer has cancelled the roadside request.',
    issueDetailsTitle: '5. Issue or Repair Details',
    issuePlaceholder: "e.g. Engine overheating, flat tire, battery won't start...",
    requestHelpBtn: 'Request Emergency Roadside Help',
    dispatching: 'Dispatching...',
    requestCreatedSuccess: 'Roadside assistance request created successfully!',
    geoNotSupported: 'Geolocation is not supported by your browser.',
    geoError: 'Could not retrieve your location. Please enable GPS permissions.',
    activeRequestTitle: 'Active Request',
    statusQueued: 'Looking for Technicians',
    statusPending: 'Pending',
    statusDispatching: 'Dispatching',
    statusAccepted: 'Technician Dispatched (On the way)',
    statusArrived: 'Technician Arrived at Location',
    statusInProgress: 'Repair In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    vehicleType: 'Vehicle Type',
    locationNotes: 'Location Notes',
    openGoogleMaps: '📍 Open Location on Google Maps',
    assignedTech: 'Assigned Technician',
    name: 'Name',
    phone: 'Phone',
    workplace: 'Workplace',
    serviceStatus: 'Service Status',
    onTheWay: 'On the way to you',
    arrivedAtLocation: 'Arrived at your location',
    currentlyRepairing: 'Currently repairing vehicle',
    workCompleted: 'Work completed',
    offersReceived: 'Available Technician Offers',
    waitingForOffers: 'Waiting for offers from nearby technicians...',
    acceptOffer: 'Accept Offer',
    rejectOffer: 'Reject',
    viewProfile: 'View Profile',
    offerRejected: 'Offer rejected',
    techAcceptedToast: 'Technician accepted! Help is on the way.',
    cancelRequestConfirm: 'Are you sure you want to cancel this request?',
    cancelRequestBtn: 'Cancel Request',
    requestCancelledSuccess: 'Request cancelled successfully',
    cancelJobConfirm: 'Are you sure you want to cancel this job and return it to the queue?',
    cancelJobBtn: 'Cancel Job',
    jobCancelledSuccess: 'Job cancelled successfully and returned to queue.',
    rateServiceTitle: 'Rate Service (Mandatory)',
    rateServiceDesc: 'Please rate the technician to complete the service and request new roadside help.',
    workQualityRating: 'Work Quality & Skills (1-5)',
    priceFairnessRating: 'Price Fairness & Honesty (1-5)',
    optionalFeedback: 'Optional feedback or comments...',
    submitRating: 'Submit Rating',
    thankYouRating: 'Thank you for rating!',
    techProfileModalTitle: 'Technician Professional Profile',
    experience: 'Experience',
    toolsEquipment: 'Tools & Equipment',
    yesEquipped: 'Yes (Fully Equipped)',
    completedJobs: 'Completed Jobs',
    overallRating: 'Overall Rating',
    qualityRating: 'Quality Rating',
    priceRating: 'Price Fairness',
    vehicleSpecialties: 'Vehicle Specialties',
    malfunctionSpecialties: 'Malfunction Specialties',
    allVehicles: 'All Vehicles',
    allMalfunctions: 'All Repairs',
    previousReviews: 'Previous Customer Reviews',
    noReviewsYet: 'No customer reviews for this technician yet.',
    newOfferReceived: 'A new technician sent you an offer!',
    requestStatusUpdated: 'Request status updated:',
    errorLoadingProfile: 'Error loading profile',
    jobsCount: 'jobs',
    assistanceSuffix: 'Assistance',
    independentSpecialist: 'Independent Specialist',

    // TechnicianDashboard
    techCenterTitle: 'Technician Command Center',
    specialties: 'Specialties',
    editSpecialties: 'Edit Specialties',
    activeJobTitle: 'Active Servicing Job',
    customer: 'Customer',
    openCustomerMaps: 'Open Customer Location on Google Maps',
    startRoute: 'Start Route',
    issueDetails: 'Issue Details:',
    markAsArrived: 'Mark as Arrived',
    startRepair: 'Start Repair',
    completeJob: 'Complete Job',
    availableRequests: 'Available Roadside Requests',
    noQueuedRequests: 'No active queued requests matching your specialties in your area.',
    offersCount: 'Offers:',
    offerSentWaiting: 'Offer Sent (Pending Customer)',
    sendOffer: 'Send Offer',
    completeActiveFirst: 'Complete Active Job First',
    sending: 'Sending...',
    offerSentSuccess: 'Offer sent to customer! Waiting for approval.',
    jobCompletedToast: 'Job completed successfully! Awaiting customer rating.',
    completeProfileTitle: 'Technician Professional Profile',
    specifySpecialtiesDesc: 'Specify your specialties and workshop info to receive matching roadside requests.',
    registeredPhone: 'Registered Phone:',
    workplacePlaceholder: 'e.g. Al-Safaa Auto Care / Independent Specialist',
    experiencePlaceholder: 'e.g. 5+ years experience in electrical & engine mechanics',
    hasToolsCheckbox: 'I have my own tools and roadside repair equipment',
    selectVehiclesPrompt: 'Vehicle Specialties (Select all that apply):',
    selectMalfunctionsPrompt: 'Malfunction Specialties (Select all that apply):',
    saveProfileBtn: 'Save Professional Details',
    profileSavedSuccess: 'Professional profile details saved successfully!',
    custAcceptedOffer: 'Customer accepted your offer! The job is assigned to you.',
    selectSpecialtiesAlert: 'Please select at least one vehicle specialty and one malfunction specialty.',
    techPhone: 'Technician Phone:',
    workplaceOrWorkshop: 'Workplace / Workshop',
    careerExperience: 'Career Experience',
    vehicleLabel: 'Vehicle:',
    addressUnlisted: 'Address details unlisted',

    // AdminDashboard
    adminPanelTitle: 'Admin Control Panel',
    tabDashboard: 'Dashboard',
    tabTransactions: 'Transactions',
    tabCustomers: 'Customers',
    tabTechnicians: 'Technicians',
    totalRequests: 'Total Requests',
    totalUsers: 'Total Users',
    completedStat: 'Completed',
    cancelledStat: 'Cancelled',
    inProgressStat: 'In Progress',
    dispatchedStat: 'Dispatched',
    queuedStat: 'Queued',
    customersStat: 'Customers',
    techniciansStat: 'Technicians',
    requestsOverview: 'Requests Overview',
    usersBreakdown: 'Users Breakdown',
    techPresence: 'Technician Presence',
    onlineTechs: 'Online Techs',
    offlineTechs: 'Offline Techs',
    allStatuses: 'All Statuses',
    allCategories: 'All Categories',
    filterAndSort: 'Filter & Sort:',
    allTechnicians: 'All Technicians',
    topOverallRating: '⭐ Top Overall Rating',
    highestQuality: 'Highest Quality',
    bestPrice: 'Best Price Fairness',
    notRatedYetFilter: 'Not Rated Yet',
    searchTechnician: 'Search technician...',
    banned: 'Banned',
    active: 'Active',
    inactive: 'Inactive',
    banUser: 'Ban User',
    unbanUser: 'Unban User',
    customerReviewsTitle: 'Customer Reviews & Comments',
    noReviewsAdmin: 'No reviews or ratings recorded for this technician yet.',
    monthlyPerformance: 'Monthly Completed Jobs Performance',
    accountStatus: 'Account Status:',
    presence: 'Presence:',
    valid: 'Valid',
    allJobsServiced: 'All Jobs Serviced by Technician',
    customerRequestsMade: 'Requests Made by Customer',
    tableId: 'ID',
    tableDate: 'Date',
    tableCustomer: 'Customer',
    tableTechnician: 'Technician',
    tableStatus: 'Status',
    tableService: 'Service',
    unassigned: 'Unassigned',
    workshopLabel: 'Workshop:',
    qualityShort: 'Quality',
    priceShort: 'Price',
    userDetails: 'Details',
    toolsAvailable: 'Tools Available:',

    // ProfilePage
    adminSecurityGate: 'Admin Security Gate',
    adminSecurityDesc: 'Please enter your password to access your profile.',
    unlockProfile: 'Unlock Profile',
    verifying: 'Verifying...',
    editProfile: 'Edit Profile',
    techProDetails: 'Technician Professional Details',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileUpdateFailed: 'Failed to update profile.',
    hasToolsFull: 'I have full roadside repair tools and equipment',
    workplaceCompany: 'Workplace / Company',
    workplaceCompanyPlaceholder: 'e.g. Al-Madina Auto Center / Independent',
    incorrectPassword: 'Incorrect password',

    // HistoryDashboard
    pastTransactions: 'Past Transactions',
    noPastTransactions: 'No transactions found.',
    performanceChart: 'Performance Chart',
    requestsActivity: 'My Requests Activity',
    myHistoryTitle: 'My Transaction History',
    last30Days: '(Last 30 Days)',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved === 'ar' || saved === 'en') ? saved : 'ar';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const toggleLang = () => {
    setLang(lang === 'ar' ? 'en' : 'ar');
  };

  const dir: 'rtl' | 'ltr' = lang === 'ar' ? 'rtl' : 'ltr';
  const isRTL = lang === 'ar';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, isRTL, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
